### ISSUE TITLE
Udělat z neměnných hodnot konstanty

### ISSUE THREAD

**Issue by fan1x** [Pavel-Hrdy/BASIC-Interpret#4]
Příklad:

https://github.com/Pavel-Hrdy/BASIC-Interpret/blob/4e05511f1a15d4f8a6cc4cf5d234cadf6d18c655/cpp_basic_interpret/exceptions.h#L13

Řádka se němění, může být konstanta

**Comment by Pavel-Hrdy** [comment]
Opraveno
