### ISSUE TITLE
`to_string` není `noexcept`

### ISSUE THREAD

**Issue by fan1x** [Pavel-Hrdy/BASIC-Interpret#5]
`to_string` neni `noexceot`, co se stane, pokud funkce vyhodí exception?

https://github.com/Pavel-Hrdy/BASIC-Interpret/blob/4e05511f1a15d4f8a6cc4cf5d234cadf6d18c655/cpp_basic_interpret/exceptions.cpp#L12

**Comment by Pavel-Hrdy** [comment]
Podle Cppreference může `std::to_string` vyhazovat jen `std::bad_alloc`, kterou vyhodí konstruktor `std::string` v případě, že už nelze alokovat novou paměť pro string. V tom případě si myslím, že nemá smysl na to nějakým způsobem reagovat, protože když už není dostatek paměti ani na alokaci stringu, tak už pravděpodobně není dostatek paměti na vypsání chybové hlášky

**Comment by fan1x** [comment]
Jasný 👍  
To, co by mě zajímalo, je, co se tedy stane, když se `std::bad_alloc` vyhodí v té funkci?

**Comment by Pavel-Hrdy** [comment]
Jestli chápu správně otázku, tak se ptáš na to, co se stane, když se vyhodí výjimka ve funkci, která je `noexcept`. V tom případě dojde k vyvolání metody `std::terminate`, která defaultně způsobí zavolání metody `std::abort`, která způsobí ukončení programu.

**Comment by fan1x** [comment]
Super :) Jen jsem chtěl vědět, jestli tomu rozumíš a víš, co to znamená a jaké to má implikace 👍
