### ISSUE TITLE
Jaký dialekt BASIC implementuješ?

### ISSUE THREAD

**Issue by fan1x** [Pavel-Hrdy/BASIC-Interpret#7]
Našel jsem spoustu dialektů na wiki a ani jeden mi nefungoval :D

**Comment by Pavel-Hrdy** [comment]
Vycházel jsem z ATARI BASIC, ze kterého jsem neimplementoval vše (např. funkce pro práci s páskou apod.) Všechny implementované funkce jsou popsané v dokumentaci.
