### ISSUE TITLE
Program by neměl obsahovat warnings 2

### ISSUE THREAD

**Issue by fan1x** [Pavel-Hrdy/BASIC-Interpret#8]
Viz obrázek, mám sice starší VS, ale myslím, že to bude i v novém... 

![error2](https://user-images.githubusercontent.com/2750870/62822070-adf07080-bb7e-11e9-9a2b-7283de8a186a.png)

**Comment by Pavel-Hrdy** [comment]
Teď už by to snad mělo být opraveno :)
